//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeChat
{
    using System;
    using System.Collections.Generic;
    //It is must using this DataAnnotations;
    using System.ComponentModel.DataAnnotations;

    public partial class book
    {
        public int BookID { get; set; }
        

        [Required(ErrorMessage ="BookName can not null!")]
        public string BookName { get; set; }


        [Required(ErrorMessage ="Author can not null!")]
        public string Author { get; set; }

        public string Publisher { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Remark { get; set; }
    }
}
